/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var sample04 = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,17],$V1=[1,18],$V2=[1,15],$V3=[1,9],$V4=[1,16],$V5=[1,8],$V6=[1,10],$V7=[1,11],$V8=[1,13],$V9=[1,21],$Va=[1,14,23,26,29,32,34,35],$Vb=[1,22],$Vc=[1,23],$Vd=[1,24],$Ve=[1,25],$Vf=[1,14,23,26,29,32,34,35,39,53,54,55,56],$Vg=[1,14,23,24,26,29,32,34,35,39,53,54,55,56],$Vh=[1,29,32,34,35],$Vi=[1,33],$Vj=[1,29,32,34],$Vk=[1,24,29,32,34,35],$Vl=[1,14,23,26,29,32,34,35,39,55,56],$Vm=[1,32,34],$Vn=[1,47],$Vo=[1,48],$Vp=[1,34],$Vq=[1,56],$Vr=[1,57],$Vs=[1,29,32,34,39,40,41];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"ALL_QUERIES":3,"QUERY":4,"SELECT_QUERY":5,"SELECT":6,"COLUMN_NAMES":7,"FROM_CLAUSE":8,"GROUP_BY_CLAUSE":9,"WHERE_CLAUSE":10,"LIMIT_AND_ORDER_CLAUSES":11,"INTO_CLAUSE":12,"VALUES":13,"FROM":14,"TABLE_VALUE":15,"SIMPLE_TABLE_VALUE":16,"SIMPLE_NAME_VALUE":17,"TABLE_NAME_VALUE":18,"REGEX_VALUE":19,"SIMPLE_NAME":20,"TABLE_NAME":21,"VALUE":22,",":23,"GROUP":24,"BY":25,"FUNCTION_CALL":26,"ORDER_CLAUSE":27,"LIMIT_CLAUSE":28,"ORDER":29,"ASC":30,"DESC":31,"LIMIT":32,"INT_VALUE":33,"INTO":34,"WHERE":35,"CONDITION":36,"BOOL_EXPRESSION":37,"(":38,")":39,"AND":40,"OR":41,"BOOL_OPERATION":42,"OPERATION_EQUAL":43,"OPERATION_NE":44,"OPERATION_GT":45,"OPERATION_LT":46,"OPERATION_GE":47,"OPERATION_LE":48,"STRING_VALUE":49,"FLOAT_VALUE":50,"DURATION_VALUE":51,"WILDCARD":52,"*":53,"/":54,"+":55,"-":56,"$accept":0,"$end":1},
terminals_: {2:"error",6:"SELECT",14:"FROM",16:"SIMPLE_TABLE_VALUE",19:"REGEX_VALUE",20:"SIMPLE_NAME",21:"TABLE_NAME",23:",",24:"GROUP",25:"BY",26:"FUNCTION_CALL",29:"ORDER",30:"ASC",31:"DESC",32:"LIMIT",33:"INT_VALUE",34:"INTO",35:"WHERE",37:"BOOL_EXPRESSION",38:"(",39:")",40:"AND",41:"OR",43:"OPERATION_EQUAL",44:"OPERATION_NE",45:"OPERATION_GT",46:"OPERATION_LT",47:"OPERATION_GE",48:"OPERATION_LE",49:"STRING_VALUE",50:"FLOAT_VALUE",51:"DURATION_VALUE",52:"WILDCARD",53:"*",54:"/",55:"+",56:"-"},
productions_: [0,[3,1],[4,1],[5,7],[7,1],[8,2],[8,2],[15,1],[15,1],[15,1],[17,1],[18,1],[13,1],[13,3],[9,3],[9,4],[9,0],[11,2],[27,2],[27,2],[27,0],[28,2],[28,0],[12,2],[12,0],[10,2],[10,0],[36,1],[36,3],[36,3],[36,3],[42,1],[42,1],[42,1],[42,1],[42,1],[42,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,1],[22,3],[22,3],[22,3],[22,3],[22,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

          this.$ = $$[$0];
          yy.Node(0,1);
          return this.$;
        
break;
case 2:

    		this.$ = $$[$0];
    	
break;
case 3:

 			this.$ = {
                COLUMN: $$[$0-5]
 			};
        
break;
case 4:

        	this.$ = $$[$0];
        
break;
case 5: case 6: case 10: case 11: case 14: case 15: case 17: case 23: case 27: case 29: case 30: case 38: case 39: case 45:


        
break;
case 12:

          this.$ = [$$[$0]];
        
break;
case 13:

          this.$.push($$[$0-2]);
          this.$.push($$[$0]);
        
break;
case 16: case 24: case 26:

          this.$ = null;
        
break;
case 18:

          this.$ = true;
        
break;
case 19: case 20:

          this.$ = false;
        
break;
case 21:


         
break;
case 22:

           this.$ = -1;
         
break;
case 25:

          this.$ = $$[$0];
        
break;
case 28:

          this.$ = $$[$0-1];
        
break;
case 37:

          this.$ = yytext;
        
break;
case 47:
  
break;
case 48:
 
break;
}
},
table: [{3:1,4:2,5:3,6:[1,4]},{1:[3]},{1:[2,1]},{1:[2,2]},{7:5,13:6,17:12,18:14,20:$V0,21:$V1,22:7,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},{8:19,14:[1,20]},{14:[2,4],23:$V9},o($Va,[2,12],{53:$Vb,54:$Vc,55:$Vd,56:$Ve}),o($Vf,[2,37]),o($Vf,[2,38]),o($Vf,[2,39]),o($Vf,[2,40]),o($Vf,[2,41]),o($Vf,[2,42]),o($Vf,[2,43]),o($Vf,[2,44]),{17:12,18:14,20:$V0,21:$V1,22:26,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},o($Vg,[2,10]),o($Vg,[2,11]),o($Vh,[2,16],{9:27,24:[1,28]}),{15:29,16:[1,30],17:31,18:32,19:$Vi,20:$V0,21:$V1},{17:12,18:14,20:$V0,21:$V1,22:34,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},{17:12,18:14,20:$V0,21:$V1,22:35,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},{17:12,18:14,20:$V0,21:$V1,22:36,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},{17:12,18:14,20:$V0,21:$V1,22:37,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},{17:12,18:14,20:$V0,21:$V1,22:38,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},{39:[1,39],53:$Vb,54:$Vc,55:$Vd,56:$Ve},o($Vj,[2,26],{10:40,35:[1,41]}),{25:[1,42]},o($Vk,[2,5]),o($Vk,[2,6]),o($Vk,[2,7]),o($Vk,[2,8]),o($Vk,[2,9]),o($Va,[2,13],{53:$Vb,54:$Vc,55:$Vd,56:$Ve}),o($Vf,[2,46]),o($Vf,[2,47]),o($Vl,[2,48],{53:$Vb,54:$Vc}),o($Vl,[2,49],{53:$Vb,54:$Vc}),o($Vf,[2,45]),o($Vm,[2,20],{11:43,27:44,29:[1,45]}),{36:46,37:$Vn,38:$Vo},{13:49,17:12,18:14,20:$V0,21:$V1,22:7,26:$V2,33:$V3,38:$V4,49:$V5,50:$V6,51:$V7,52:$V8},{1:[2,24],12:50,34:[1,51]},o($Vp,[2,22],{28:52,32:[1,53]}),{30:[1,54],31:[1,55]},o($Vj,[2,25],{40:$Vq,41:$Vr}),o($Vs,[2,27]),{36:58,37:$Vn,38:$Vo},o($Vh,[2,14],{23:$V9,26:[1,59]}),{1:[2,3]},{15:60,17:31,18:32,19:$Vi,20:$V0,21:$V1},o($Vp,[2,17]),{33:[1,61]},o($Vm,[2,18]),o($Vm,[2,19]),{36:62,37:$Vn,38:$Vo},{36:63,37:$Vn,38:$Vo},{39:[1,64],40:$Vq,41:$Vr},o($Vh,[2,15]),{1:[2,23]},o($Vp,[2,21]),o($Vs,[2,29]),o([1,29,32,34,39,41],[2,30],{40:$Vq}),o($Vs,[2,28])],
defaultActions: {2:[2,1],3:[2,2],50:[2,3],60:[2,23]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 'MERGE';
break;
case 1:return 'LIST';
break;
case 2:return 'SERIES'
break;
case 3:return 'CONTINUOUS_QUERY'
break;
case 4:return 'CONTINUOUS_QUERIES'
break;
case 5:return 'INNER'
break;
case 6:return 'JOIN'
break;
case 7:this.begin("FROM_CLAUSE"); return 14
break;
case 8: this.begin("IN_REGEX");   
break;
case 9:
   

break;
case 10:
  

break;
case 11:
  this.begin("INITIAL");
  console.log("-----------xxxxxxx", yy_.yytext);
  return "REGEX_STRING";

break;
case 12:
  this.begin("INITIAL");
  return "INSENSITIVE_REGEX_STRING";

break;
case 13: 
  console.log("-----------vvvvvvvv", yy_.yytext);
  return "REGEX_STRING";

break;
case 14: this.begin('INITIAL'); return "WHERE"; 
break;
case 15:return 'AS'
break;
case 16:return 6
break;
case 17:return 'EXPLAIN'
break;
case 18:return 'DELETE'
break;
case 19:this.begin('INITIAL'); return 'DROP_SERIES';
break;
case 20:return 'DROP'
break;
case 21:return 32
break;
case 22:return 29
break;
case 23:return 30
break;
case 24:return 'IN'
break;
case 25:return 31
break;
case 26:return 24
break;
case 27:return 25
break;
case 28:return 34
break;
case 29:return yy_.yytext
break;
case 30:return yy_.yytext
break;
case 31:return yy_.yytext
break;
case 32:return yy_.yytext
break;
case 33:return yy_.yytext
break;
case 34:return yy_.yytext
break;
case 35:return 40
break;
case 36: return yy_.yytext; 
break;
case 37:return 41
break;
case 38:return 'REGEX_OP'
break;
case 39:return 43
break;
case 40:return 'NEGATION_REGEX_OP'
break;
case 41:return 44
break;
case 42:return 46
break;
case 43:return 45
break;
case 44:return 48
break;
case 45:return 47
break;
case 46: return yy_.yytext; 
break;
case 47:/* skip whitespace */
break;
case 48:return 49
break;
case 49:  return 'DURATION'; 
break;
case 50:  return 50; 
break;
case 51: return "SIMPLE_NAME"; 
break;
case 52:return  "TABLE_NAME";
break;
case 53:return 'EOF'
break;
}
},
rules: [/^(?:merge\b)/i,/^(?:list\b)/i,/^(?:series\b)/i,/^(?:continuous query\b)/i,/^(?:continuous queries\b)/i,/^(?:inner\b)/i,/^(?:join\b)/i,/^(?:from\b)/i,/^(?:\/)/i,/^(?:\\\/)/i,/^(?:\\)/i,/^(?:\/)/i,/^(?:\/i\b)/i,/^(?:[^\\/]*)/i,/^(?:where\b)/i,/^(?:as\b)/i,/^(?:select\b)/i,/^(?:explain\b)/i,/^(?:delete\b)/i,/^(?:drop series\b)/i,/^(?:drop\b)/i,/^(?:limit\b)/i,/^(?:order\b)/i,/^(?:asc\b)/i,/^(?:in\b)/i,/^(?:desc\b)/i,/^(?:group\b)/i,/^(?:by\b)/i,/^(?:into\b)/i,/^(?:\()/i,/^(?:\))/i,/^(?:\+)/i,/^(?:-)/i,/^(?:\*)/i,/^(?:\/)/i,/^(?:and\b)/i,/^(?:\.)/i,/^(?:or\b)/i,/^(?:=~)/i,/^(?:=)/i,/^(?:!~)/i,/^(?:<>)/i,/^(?:<)/i,/^(?:>)/i,/^(?:<=)/i,/^(?:>=)/i,/^(?:;)/i,/^(?:\s+)/i,/^(?:(['](\\.|[^']|\\')*?['])+)/i,/^(?:([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)[usmhdw])/i,/^(?:[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)/i,/^(?:[a-zA-Z0-9_][a-zA-Z0-9._-]*)/i,/^(?:[:\[a-zA-Z0-9_][:\[\]a-zA-Z0-9._-]*)/i,/^(?:<\*><<EOF>>)/i],
conditions: {"IN_REGEX":{"rules":[9,10,11,12,13],"inclusive":false},"FROM_CLAUSE":{"rules":[0,1,2,3,4,5,6,7,8,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53],"inclusive":true},"REGEX_CONDITION":{"rules":[0,1,2,3,4,5,6,7,8,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53],"inclusive":true},"INITIAL":{"rules":[0,1,2,3,4,5,6,7,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = sample04;
exports.Parser = sample04.Parser;
exports.parse = function () { return sample04.parse.apply(sample04, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}